---
- hosts: all
  gather_facts: false
  remote_user: root
  tasks:
    - name: Fetch files from the remote server
      synchronize:
        src:  /var/lib/jenkins/workspace/myjob-cicd
        dest: /root/project/
        mode: pull
        
    - name: Stop and remove the container
      block:
        - name: Stopping the container
          docker_container:
            name: nginx_container
            image: nginx_image:v1
            state: stopped

        - name: Removing the container 
          docker_container:
            name: nginx_container
            image: nginx_image:v1
            state: absent
      when: "'nginx_container' in docker_containers.stdout_lines"

    - name: Delete the old image
      docker_image:
        name: nginx_image:v1
        state: absent

    - name: Build the Docker image
      docker_image:
        name: nginx_image:v1
        source: build
        build:
          path: /root/project
        state: present

    - name: Create and start the container
      docker_container:
        name: nginx_container
        image: nginx_image:v1
        ports:
          - "80:80"
        state: started

